/*Getters */
//General
export const BCARDS_QUANTITIES = 'bcards/BCARDS_QUANTITIES';
export const BCARDS_SIZES = 'bcards/BCARDS_SIZES';
export const BCARDS_SIDES = 'bcards/BCARDS_SIDES';
export const BCARDS_PAPERS = 'bcards/BCARDS_SIDES';
export const BCARDS_TREATMENTS = 'bcards/BCARDS_TREATMENTS';
export const BCARDS_ADDONS = 'bcards/BCARDS_ADDONS';
export const BCARDS_DESIGNS = 'bcards/BCARDS_DESIGNS';
export const BCARDS_PAPER_TREATMENTS = 'bcards/BCARDS_TREATMENTS';
export const BCARDS_MYPRODUCTJSON = 'bcards/BCARDS_MYPRODUCTJSON';
export const BCARDS_CONSTANTS = 'bcards/BCARDS_CONSTANTS';
//myProduct
export const BCARDS_MYQUANTITY = 'bcards/BCARDS_MYQUANTITY';
export const BCARDS_MYSIZE = 'bcards/BCARDS_MYSIZE';
export const BCARDS_MYSIDE = 'bcards/BCARDS_MYSIDE';
export const BCARDS_MYPAPER = 'bcards/BCARDS_MYPAPER';
export const BCARDS_MYTREATMENTS = 'bcards/BCARDS_MYTREATMENTS';
export const BCARDS_MYPRICE = 'bcards/BCARDS_MYPRICE';
export const BCARDS_MYPRODUCT = 'bcards/BCARDS_MYPRODUCT';
/*Mutations*/
export const MUTATION_BCARDS_MYQUANTITY = 'bcards/MUTATION_BCARDS_MYQUANTITY';
export const MUTATION_BCARDS_MYSIZE = 'bcards/MUTATION_BCARDS_MYSIZE';
export const MUTATION_BCARDS_MYSIDE = 'bcards/MUTATION_BCARDS_MYSIDE';
export const MUTATION_BCARDS_MYPAPER = 'bcards/MUTATION_BCARDS_MYPAPER';
export const MUTATION_BCARDS_MYTREATMENTS = 'bcards/MUTATION_BCARDS_MYTREATMENTS';
export const MUTATION_BCARDS_MYPRICE = 'bcards/MUTATION_BCARDS_MYPRICE';
export const MUTATION_BCARDS_MYPRODUCTJSON = 'bcards/MUTATION_BCARDS_MYPRODUCTJSON';
export const MUTATION_BCARDS_MYPRODUCT = 'bcards/MUTATION_BCARDS_MYPRODUCT';
export const MUTATION_BCARDS_PAPER_TREATMENTS = 'bcards/MUTATION_BCARDS_PAPER_TREATMENTS';
export const MUTATION_BCARDS_MYADDONS = 'bcards/MUTATION_BCARDS_MYADDONS';
export const MUTATION_BCARDS_QTYPRICE = 'bcards/MUTATION_BCARDS_QTYPRICES';
/* Actions */
export const ACTION_BCARDS_MYQUANTITY = 'bcards/ACTION_BCARDS_MYQUANTITY';
export const ACTION_BCARDS_MYSIZE = 'bcards/ACTION_BCARDS_MYSIZE';
export const ACTION_BCARDS_MYSIDE = 'bcards/ACTION_BCARDS_MYSIDE';
export const ACTION_BCARDS_MYPAPER = 'bcards/ACTION_BCARDS_MYPAPER';
export const ACTION_BCARDS_MYTREATMENTS = 'bcards/ACTION_BCARDS_MYTREATMENTS';
export const ACTION_BCARDS_MYPRICE = 'bcards/ACTION_BCARDS_MYPRICE';
export const ACTION_BCARDS_MYPRICEPERCARD = 'bcards/ACTION_BCARDS_MYPRICEPERCARD';
export const ACTION_BCARDS_MYPRODUCTJSON = 'bcards/ACTION_BCARDS_MYPRODUCTJSON';
export const ACTION_BCARDS_MYPRODUCT = 'bcards/ACTION_BCARDS_MYPRODUCT';
export const ACTION_BCARDS_PRINTING_SIDES = 'bcards/ACTION_BCARDS_PRINTING_SIDES';
export const ACTION_BCARDS_MYADDONS = 'bcards/ACTION_BCARDS_MYADDONS';
export const ACTION_BCARDS_QTYPRICES = 'bcards/ACTION_BCARDS_QTYPRICES';